import { arrow, spark, projectCover, projectCards } from '../components/site.mjs';
import { projects } from '../content/projects.mjs';

export const home = `
<section class="hero">
  <svg class="hero-wave" viewBox="0 0 1400 760" preserveAspectRatio="none" aria-hidden="true"><path d="M620 790C430 480 1090 610 1040 310S1300-50 1460-70V800Z" fill="#d6e8ac"/><path d="M990 790c-70-130 190-290 260-90s230 45 230 45v70Z" fill="#efa366"/></svg>
  <div class="hero-copy"><p class="intro-label"><span class="status-dot"></span>Osama Zuraid · Computer engineer</p><h1>Code meets<br>the real<br>world.</h1><p class="hero-description">From a line of C to a working system.<br>I build software, explore hardware, and care<br class="desktop-break"> about the people on the other side.</p><a class="button button-pink" href="#selected-work">Explore my work ${arrow}</a></div>
  <div class="hero-objects" aria-label="Featured project covers">
    <div class="object-float object-back"><a class="book-object" data-tilt href="aid.html" aria-label="Explore the aid distribution project">${projectCover(projects[0], 'book-face')}<span class="book-spine" aria-hidden="true"></span><span class="book-pages" aria-hidden="true"></span></a></div>
    <div class="object-float object-front"><a class="book-object" data-tilt href="embedded.html" aria-label="Explore the bare-metal controller project">${projectCover(projects[1], 'book-face')}<span class="book-spine" aria-hidden="true"></span><span class="book-pages" aria-hidden="true"></span></a></div>
    <span class="hero-spark" aria-hidden="true">${spark}</span><span class="hand-note">a little software.<br>a little silicon.<svg viewBox="0 0 90 60" fill="none" aria-hidden="true"><path d="M4 4c50 0 0 44 73 39m-14-13 16 13-18 12" stroke="currentColor" stroke-width="2"/></svg></span>
  </div>
  <div class="hero-bottom"><span>Built with curiosity. Based in Gaza.</span><button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button><a href="#selected-work">Scroll to explore ↓</a></div>
</section>
<section class="selected-work content-width" id="selected-work"><div class="section-heading"><div><p class="section-kicker">A few things I’ve built</p><h2>Open a project.<br>See what’s inside.</h2></div><a class="text-link" href="work.html">All seven projects ${arrow}</a></div>${projectCards(projects.slice(0, 4))}</section>
<section class="feature section-shell"><div class="feature-visual"><span class="feature-outline" aria-hidden="true"></span><img src="assets/images/controller-concept.webp" width="960" height="971" alt="Concept illustration of an exploded microcontroller enclosure with a purple circuit board" decoding="async"><span class="image-note">Concept illustration</span></div><div class="feature-copy"><p class="section-kicker">Software, meet hardware.</p><h2>Good things<br>happen under<br>the hood.</h2><p>Interrupts. Timers. A register that finally does what you intended. My embedded work starts with understanding the small things that make a system run.</p><a class="button button-dark" href="embedded.html">Inside the controller ${arrow}</a><span class="feature-note">C + ARM + a lot of curiosity.</span></div></section>
<section class="process-section content-width"><div class="section-heading"><h2>How I make<br>things happen.</h2><p>From “what if?”<br>to “it works.”</p></div><div class="process-grid">
<article class="process-card color-cyan"><span>Step 01</span><div class="process-art" aria-hidden="true">?</div><h3>Understand<br>the problem.</h3><p>Start with the people, the constraints, and the right questions.</p></article>
<article class="process-card color-pink"><span>Step 02</span><div class="process-art sketch" aria-hidden="true">↗</div><h3>Map out<br>the idea.</h3><p>Break it down. Trace the data. Make the choices clear.</p></article>
<article class="process-card color-yellow"><span>Step 03</span><div class="process-art code-art" aria-hidden="true">{ }</div><h3>Build it.<br>Bit by bit.</h3><p>Small working pieces, brought together with care.</p></article>
<article class="process-card color-lavender"><span>Step 04</span><div class="process-art" aria-hidden="true">✓</div><h3>Test. Learn.<br>Make it better.</h3><p>Check the result, understand the failure, and keep improving.</p></article></div></section>
<section class="skills-section section-shell"><span class="skills-outline outline-one" aria-hidden="true"></span><span class="skills-outline outline-two" aria-hidden="true"></span><p class="section-kicker">Different tools. Same curiosity.</p><h2>Embedded systems.<br>Backend development.<br><span>And the space between.</span></h2><p>Control, signals, computer vision.<br>I like knowing how the pieces connect.</p><span class="skills-spark" aria-hidden="true">${spark}</span></section>
<div class="technology-strips" aria-label="Technologies I work with"><div>C / C++ <span>✳</span> Python <span>✳</span> TypeScript <span>✳</span> ARM <span>✳</span> PostgreSQL</div><div>Build it. Understand it. Make it useful. <span>✳</span> Build it. Understand it.</div></div>
<section class="about-teaser section-shell"><div class="about-copy"><p class="section-kicker">A little about me</p><h2>An engineer.<br>A curious human.</h2><p>I’m Osama, a computer engineer from Gaza. My path runs from hands-on humanitarian data work to backend services and the registers inside a microcontroller.</p><p>The thread through it all? Making something useful, and understanding why it works.</p><a class="button button-dark" href="about.html">Meet the person behind the code ${arrow}</a></div><div class="about-note"><span class="note-pin" aria-hidden="true"></span><span class="note-heading">Things I believe</span><p>Start with a real problem.<br>Keep asking questions.<br>Leave it better<br>than you found it.</p><span class="note-signature">— Osama</span></div></section>
`;
