// Descriptions adapted from the user's original portfolio and existing case studies.
// A missing repository URL is intentional: do not present a profile as project source.
export const projects = [
  {
    id: 'aid', title: 'Aid distribution', full: 'Humanitarian Aid Distribution System',
    cover: 'Built for\npeople.', color: 'purple', kind: 'aid', category: 'Full-stack',
    status: 'Personal project', year: '2025', href: 'aid.html',
    stack: ['NestJS', 'TypeScript', 'PostgreSQL', 'React'],
    summary: 'A clear record of who received what, and when.',
    description: 'A system for registering displaced people and recording food and non-food distributions. The idea grew from my experience maintaining records at UNRWA: useful software begins with understanding the people who need it.',
    problem: 'Registration and distribution records need to answer a practical question: who has received assistance, and who still needs it?',
    contribution: 'Built a registration and distribution platform using NestJS, TypeScript, Prisma, PostgreSQL and React. The workflow connects people to their distribution records.',
    focus: ['Registration of displaced people', 'Food and non-food distribution records', 'Clear distribution history'],
  },
  {
    id: 'embedded', title: 'Bare-metal controller', full: 'Bare-Metal Embedded Controller',
    cover: 'Closer to\nthe metal.', color: 'cyan', kind: 'chip', category: 'Embedded',
    status: 'Academic project', year: '2024', href: 'embedded.html',
    stack: ['C', 'ARM Assembly', 'Cortex-M'],
    summary: 'Registers, interrupts and the details underneath.',
    description: 'Firmware that talks directly to hardware registers, with no operating system in between. This project brought together interrupts, timers, sensor inputs and peripheral communication.',
    problem: 'Understand how a microcontroller responds to inputs and controls peripherals at the register level.',
    contribution: 'Worked with C and ARM Assembly to implement interrupt handlers, timers, ADC and peripheral communication through SPI, I2C and UART.',
    focus: ['Register-level firmware', 'Interrupts, timers and ADC', 'SPI, I2C and UART'],
  },
  {
    id: 'cnn', title: 'CNN from scratch', full: 'CNN from scratch',
    cover: 'A little\nneural magic.', color: 'pink', kind: 'network', category: 'Neural networks',
    status: 'Released · v0.1.0', year: 'v0.1.0', href: 'cnn.html',
    stack: ['Python', 'C / C++', 'VHDL'],
    summary: 'Train in NumPy. Run in C. Check every layer.',
  },
  {
    id: 'shell', title: 'Unix shell', full: 'Unix Shell',
    cover: 'Under the\ncommand line.', color: 'yellow', kind: 'terminal', category: 'Systems',
    status: 'Academic project', year: '2023', href: 'shell.html',
    stack: ['C', 'Linux', 'Signals'],
    summary: 'A shell built from the operating system’s basics.',
    description: 'A Unix shell written in C, with more than 15 commands, process control and signal handling. Building it made the mechanics behind everyday terminal commands much more concrete.',
    problem: 'Explore how a shell starts processes, handles signals and coordinates foreground and background jobs.',
    contribution: 'Implemented command handling with fork and execvp, alongside signal handling for foreground and background processes.',
    focus: ['15+ commands', 'Process creation with fork and execvp', 'Foreground and background signal handling'],
  },
  {
    id: 'home', title: 'IoT smart home', full: 'IoT Smart Home System',
    cover: 'A home\nwith senses.', color: 'orange', kind: 'home', category: 'IoT',
    status: 'Graduation project', year: '2023', href: 'smart-home.html',
    stack: ['ESP8266', 'C', 'Sensors'],
    summary: 'Gas, motion and climate sensing. All on the device.',
    description: 'A multi-sensor smart home system on an ESP8266. Gas, motion, temperature and humidity sensing run locally, with no server or cloud dependency.',
    problem: 'Build useful sensor-driven behavior in an environment with intermittent power and unreliable connectivity.',
    contribution: 'Combined multiple sensors with local decision logic on an ESP8266. Keeping the logic on the device was a practical response to the conditions in which I built the project.',
    focus: ['Gas and motion sensing', 'Temperature and humidity monitoring', 'On-device logic without a cloud service'],
  },
  {
    id: 'vision', title: 'Image processing', full: 'Image Processing Toolkit',
    cover: 'A different\nway to see.', color: 'lavender', kind: 'vision', category: 'Computer vision',
    status: 'Academic project', year: '2022', href: 'image-processing.html',
    stack: ['MATLAB', 'Python'],
    summary: 'Finding edges, reducing noise and seeing patterns.',
    description: 'An exploration of the fundamentals behind machine vision: edge detection, noise reduction, segmentation and feature extraction using MATLAB and Python.',
    problem: 'Understand how numerical operations on pixels reveal structure in an image.',
    contribution: 'Implemented and explored convolutions and thresholds for image processing, connecting the mathematical operations to their visible effects.',
    focus: ['Edge detection and noise reduction', 'Segmentation', 'Feature extraction'],
  },
  {
    id: 'cortex', title: 'An integer CNN', full: 'The Cortex-M4 experiment',
    cover: 'Big ideas.\nFewer bits.', color: 'mint', kind: 'chip', category: 'Embedded ML',
    status: 'Planned', year: 'Next up', href: 'cortex.html',
    stack: ['Embedded C', 'int8', 'QEMU'],
    summary: 'The next question: how small can inference go?',
  },
  {
    id: 'neurontrade', title: 'NeuronTrade', full: 'NeuronTrade — Paper Trading & Research',
    cover: 'Measure first.\nTrade on paper.', color: 'mint', kind: 'trading', category: 'Python systems',
    status: 'Public demo · Paper only', year: '2026', href: 'neurontrade.html',
    stack: ['Python', 'SQLite', 'ZeroMQ', 'pytest'],
    repository: 'https://github.com/osama-z/bottrade-v1',
    summary: 'Simulated trading, persistent risk controls, and research that tests its own assumptions.',
    description: 'A public paper trading and quantitative research demo. Market data flows through indicators and strategies into risk checks, simulated execution and a SQLite audit trail. Live and testnet executors are disabled in this version; it is an educational engineering project with no proven trading edge.',
    problem: 'A backtest can look convincing while hiding inconsistent sizing, trading costs or selection bias. The challenge was to build a system whose decisions and research results could be inspected and tested.',
    contribution: 'Built a modular Python pipeline with Decimal-based position sizing, persistent circuit breakers, paper execution and backtesting. Shared decision logic and regression tests check consistency between simulation paths. Documented out-of-sample experiments that rejected promising in-sample results.',
    focus: ['Simulated execution and SQLite persistence', 'Position sizing, portfolio heat limits and manual-reset circuit breakers', 'Shared strategy decisions across backtests and paper trading', 'Out-of-sample validation that exposed selection bias', 'Disabled live and testnet executors in the public demo'],
  },
];
